spring.application.name=sign-service
server.port=8081

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sign?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hinovaUser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:hinovaPassword}
logging.level.org.hibernate.orm.connections.pooling=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.hibernate=ERROR

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.admin.auto-create=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
app.kafka.topics.contract-signed=${KAFKA_TOPIC_CONTRACT_SIGNED:contract-signed.v1}

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
