server.port=8081

spring.datasource.url=jdbc:mysql://mysql-sign:3306/sign?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=hinovaUser
spring.datasource.password=hinovaPassword

spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=kafka:9092
app.kafka.topics.contract-signed=contract-signed.v1
