spring.application.name=sign-service
server.port=8081

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sign?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hinovaUser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:hinovaPassword}
logging.level.org.hibernate.orm.connections.pooling=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.hibernate=ERROR

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Integration
crm.base-url=${CRM_BASE_URL:http://localhost:8080}

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html