server.port=8080

spring.datasource.url=jdbc:mysql://mysql-crm:3306/crm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=hinovaUser
spring.datasource.password=hinovaPassword

spring.jpa.hibernate.ddl-auto=update

sign.base-url=http://sign-service:8081